# Generated by Django 4.2.3 on 2023-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_ids', models.IntegerField()),
                ('prod_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prod_desc', models.TextField()),
                ('prod_img_1', models.ImageField(upload_to='')),
                ('prod_img_2', models.ImageField(upload_to='')),
                ('prod_img_3', models.ImageField(upload_to='')),
                ('prod_img_4', models.ImageField(upload_to='')),
                ('prod_tag', models.CharField(max_length=10)),
            ],
        ),
    ]
