# Generated by Django 4.2.3 on 2023-07-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prod_img_4',
        ),
    ]
