# Generated by Django 4.2.3 on 2023-07-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0002_remove_products_prod_img_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_img_1',
            field=models.ImageField(upload_to='prodImg'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_img_2',
            field=models.ImageField(upload_to='prodImg'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_img_3',
            field=models.ImageField(upload_to='prodImg'),
        ),
    ]
