# Generated by Django 4.2.3 on 2023-07-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0003_alter_products_prod_img_1_alter_products_prod_img_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prod_tag',
            new_name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='subCategory',
            field=models.CharField(default='', max_length=10),
        ),
    ]
