# Generated by Django 4.2.3 on 2023-07-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerceapp', '0002_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
